### PR TITLE
added "main" to package.json

### PR DESCRIPTION
**Pull request by hellatan**
gives the ability to just do require('jquery-operator');
instead of needing to require individual files

### CODE REVIEW

**Comment by lilianammmatos** [comment]
Good idea. There are only two cases where only one of the two files is required : `home.js` and `ads_spec.js`. I don't think requiring the other file would pose a problem. This looks good to me.

**Comment by hellatan** [comment]
merge it :100:

**Comment by hellatan** [comment]
$ npm publish
+ jquery-operator@1.1.1

**Comment by lilianammmatos** [comment]
Do I need to do that?

**Comment by hellatan** [comment]
sorry, i meant it was published to that version

**Pull request merged**
